"""last_updated cloumn added.

Revision ID: 84e0126efd84
Revises: 858970daf80e
Create Date: 2024-10-13 21:51:36.399765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e0126efd84'
down_revision = '858970daf80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_notes_created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_created_at', ['created_at'], unique=False)
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
