"""Initial migration.

Revision ID: 858970daf80e
Revises: 
Create Date: 2024-10-13 21:43:31.147422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858970daf80e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_created_at'))

    # ### end Alembic commands ###
